apiVersion: v1
kind: Service
metadata:
  name: budget-tracker-react-service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: budget-tracker-react
  ports:
    - port: 80
      targetPort: 80
